import AOSInit from "./_components/aos";
import Footer from "./_components/layout/footer";
import Header from "./_components/layout/header";
import "./globals.css";

export const metadata = {
  title: "Genz Diamonds",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <AOSInit />
      </body>
    </html>
  );
}
